// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDijFZB_-p2eW0aaxcZW1QLHaChaiuUFM',
    appId: '1:892245777388:web:e0e6b92f023d78e8f73ec9',
    messagingSenderId: '892245777388',
    projectId: 'talksy-99888',
    authDomain: 'talksy-99888.firebaseapp.com',
    storageBucket: 'talksy-99888.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzWjyCvEymStbfzHnqOs6gMhMA4giY8yw',
    appId: '1:892245777388:android:ced27b6f67d38e88f73ec9',
    messagingSenderId: '892245777388',
    projectId: 'talksy-99888',
    storageBucket: 'talksy-99888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX2-fRXrs0iIKrQGTWgc3JukWiFPJhiJA',
    appId: '1:892245777388:ios:1ba860655c51a8f2f73ec9',
    messagingSenderId: '892245777388',
    projectId: 'talksy-99888',
    storageBucket: 'talksy-99888.firebasestorage.app',
    iosBundleId: 'com.example.talksy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX2-fRXrs0iIKrQGTWgc3JukWiFPJhiJA',
    appId: '1:892245777388:ios:1ba860655c51a8f2f73ec9',
    messagingSenderId: '892245777388',
    projectId: 'talksy-99888',
    storageBucket: 'talksy-99888.firebasestorage.app',
    iosBundleId: 'com.example.talksy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDijFZB_-p2eW0aaxcZW1QLHaChaiuUFM',
    appId: '1:892245777388:web:9af76597b047cf03f73ec9',
    messagingSenderId: '892245777388',
    projectId: 'talksy-99888',
    authDomain: 'talksy-99888.firebaseapp.com',
    storageBucket: 'talksy-99888.firebasestorage.app',
  );
}
